services:
  backend:
    image: mopperman/lehmer-backend:latest
    container_name: lehmer_backend
    environment:
      - FLASK_PORT=5050
      - FLASK_DEBUG=False
      - FLASK_HOST=0.0.0.0
      - FLASK_CORS=False
    ports:
      - "5050:5050"
    networks:
      - lehmer_network
    restart: unless-stopped

  frontend:
    image: mopperman/lehmer-frontend:latest
    container_name: lehmer_frontend
    environment:
      - VITE_API_URL=http://lehmer_backend:5050
      - FRONTEND_PORT=5173
    ports:
      - "5173:5173"
    networks:
      - lehmer_network
    restart: unless-stopped

networks:
  lehmer_network:
    driver: bridge
