version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
      args:
        FLASK_PORT: 5050
    container_name: lehmer_backend
    environment:
      - FLASK_PORT=5050
      - FLASK_DEBUG=False
      - FLASK_HOST=0.0.0.0
      - FLASK_CORS=True
    ports:
      - "5050:5050"
    networks:
      - lehmer_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
      args:
        VITE_API_URL: http://lehmer_backend:5050
        FRONTEND_PORT: 5173
    container_name: lehmer_frontend
    environment:
      - VITE_API_URL=http://lehmer_backend:5050
      - FRONTEND_PORT=5173
    ports:
      - "5173:5173"
    networks:
      - lehmer_network
    restart: unless-stopped

networks:
  lehmer_network:
    driver: bridge
