services:
  backend:
    image: mopperman/lehmer-backend:latest
    container_name: lehmer_backend
    environment:
      - FLASK_DEBUG=False
      - FLASK_PORT=5050
      - FLASK_HOST=127.0.0.1
      - FLASK_CORS=False
    ports:
      - "5050:5050"
    restart: always

  frontend:
    image: mopperman/lehmer-frontend:latest
    container_name: lehmer_frontend
    environment:
      - VITE_API_BASE_URL=https://lehmer.mopper.dev
    ports:
      - "49139:49139"
    restart: always
