name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

env:
  FORCE_COLOR: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Render the documentation
      run: >
        sphinx-build
        -M html ./docs ./docs/_build
        -vv
        --jobs=auto
        --show-traceback
        --keep-going