name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

env:
  FORCE_COLOR: "1"

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DOC_PAGE_SECRET }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
