name: Python application

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

      - name: Installing package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Building documentation
        run: |
          sphinx-apidoc -o . .. ../*tests*
          sphinx-build -b html docs/ public/

      # upload artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: public

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Location check
        run: echo "Currently on ${{ github.ref }}"

      # download docs artifacts and publish them
      - uses: actions/download-artifact@v1
        with:
          name: documentation
          path: public
      - name: Deploy docs to github pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public

      # download packages and publish them
      - uses: actions/setup-python@v1
        with:
          python-version: '3'
          architecture: 'x64'
