name: Documentation

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test correctness of documentation
      run: |
        python .\docs\doc_test.py -p . -i rivertz | tee ./correct_documentation.txt

    - name: Check for failed tests
      id: check_tests
      run: |
        if grep -q "No issues found with the documentation!" correct_documentation.txt; then
          echo "DOCS_CHECK=Passed" >> $GITHUB_ENV
        else
          echo "DOCS_CHECK=Failed" >> $GITHUB_ENV
        fi

    - name: Create Documentation Status Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: lehmer-docs-status.json
        label: 'Docs Check Status'
        message: ${{ env.DOCS_CHECK }}
        color: ${{ env.DOCS_CHECK == 'passed' && '00FF00' || 'FF0000' }}

    - name: Building documentation
      run: |
        sphinx-apidoc -o . .. ../*tests*
        sphinx-build -b html docs/ public/

    - uses: actions/upload-pages-artifact@v3
      with:
        path: public

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
