name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

env:
  FORCE_COLOR: "1"

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DOC_PAGE_SECRET }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
