# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create coverage report
      id: create_coverage_report
      run: |
        pytest --cov-report=html --cov=./ tests/

    - name: Get the percentage
      id: parse_coverage
      run: |
        echo "COVERAGE=$(grep -oP '(?<=<span class="pc_cov">)\d+%' ./htmlcov/index.html | head -n 1 | tr -d '%')" >> $GITHUB_ENV

    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 9010143336585a9f9ff81a9ec805a0b0
        filename: lehmer-coverage.json # Use test.svg if you want to use the SVG mode.
        label: Coverage
        message: ${{ env.COVERAGE }}%
        valColorRange: ${{ env.COVERAGE }}
        maxColorRange: 100
        minColorRange: 0
